### ISSUE TITLE
0.7.2.zip source archive is empty

### ISSUE THREAD

**Issue by efx** [AKASHAorg/Community#304]
#### System information
linux
AKASHA version: `0.7.2 `

Operating System: ` GNU/Linux`

#### Expected behaviour
I expected to download the akasha application and compile from source.

#### Actual behaviour
I downloaded the `0.7.2.zip` file from https://github.com/AkashaProject/dapp/releases but found it only contained the `issue_template.md` and the `README.md`.

#### Steps to reproduce the problem

1. Download https://github.com/AkashaProject/dapp/releases/download/0.7.2/AKASHA-0.7.2.zip"
2. unzip somewhere on your machine
3. notice there is nothing besides those 2 `md` files

**Comment by SeverS** [comment]
Hey @efx, which operating system do you use?
That .zip file is for linux!

**Comment by efx** [comment]
@SeverS As I noted above, I am using Linux (nixOS specifically). I'm aware the zip is for Linux; that is why I tried it.

**Comment by ligi** [comment]
Unfortunately the source code of akasha is not yet released :-( 
also waiting for this ..
